### ISSUE TITLE
ERROR: Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by roperi** [roperi/YaSaas#1]
Reported by a  Windows user while installing requirements.txt file

**Comment by roperi** [comment]
Closing as user hasn't reported back.

**Comment by JohnnDx** [comment]
Had the same issue on Windows:

Changed 

backports.zoneinfo==0.2.1

to 

backports.zoneinfo;python_version<"3.9"

in backend/requirements.txt

and it works for me.
