### ISSUE TITLE
404 errors in http://localhost:3000/

### ISSUE THREAD

**Issue by adrianreal** [roperi/YaSaas#5]
Hi, I am following the README. However, after reaching the step 
```
3. View the application
Go to http://localhost:3000/ to view the application.
```
I tried going into tabs like "SIGNUP", "PRODUCTS", I got "404 - Not found" displayed. May I know if this is normal?

Furthermore, in the next step:
`Go to http://127.0.0.1:8000/admin to access the Django Admin interface and sign in using the admin credentials.` 
I keep getting this eerror: "A server error occurred.  Please contact the administrator." Not sure how to resolve this.

**Comment by roperi** [comment]
> A server error occurred. Please contact the administrator.

Please set `Debug = True` in your `backend/settings.py` file to see the full traceback error message and report back.

**Comment by adrianreal** [comment]
Tried that and it just gives some warnings like: `The directory [my root path]/backend/static/custom' in the STATICFILES_DIRS setting does not exist.

However, it seems that after I did the following 3 things, the issues are all resolved and I'm able to access the Pricing Table and Sign In/Sign Up .
**1) Accessing PricingTable**: Changing the custom buttons from href to RouterLink in Header.tsx. For example,
```
            <RouterLink to='/pricing-table' style={{ textDecoration: 'none' }}>
              <Button>Pricing</Button>
            </RouterLink>
```

**2) Accessing Sign Up**: For this issue, changing the secret key definition in backend/backend/settings.py worked for me. Specifically, I changed from
`SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')`
into
`SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-default-secret-key')`

New to Django, so not too sure what exact reasons causing those. But these modifications worked well for me.

**Comment by adrianreal** [comment]
I tried that and it only gives some warnings like: `The directory [my root path]/backend/static/custom' in the STATICFILES_DIRS setting does not exist.

However, it seems that after I did the following 3 things, the issues are all resolved and I'm able to access the Pricing Table and Sign In/Sign Up .
**1) Accessing PricingTable**: Changing the custom buttons from href to RouterLink in Header.tsx. For example,
```
            <RouterLink to='/pricing-table' style={{ textDecoration: 'none' }}>
              <Button>Pricing</Button>
            </RouterLink>
```

**2) Accessing Sign Up**: For this issue, changing the secret key definition in backend/backend/settings.py worked for me. Specifically, I changed from
`SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')`
into
`SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-default-secret-key')`

Do you know what may be causing the differences? I'm new to Django, so still figuring out. But these modifications worked well for me so far.

[EDIT]: Regarding 2, I think it is due to I did not conduct the secret-key setting at **Configurations** step yet. Still not too sure about 1.

**Comment by roperi** [comment]
```
The directory [my root path]/backend/static/custom' in the STATICFILES_DIRS setting does not exist.
```

Django is complaining this custom static folder doesn't exists -which is true. Originally this backend folder was erroneously holding the logo image used in the homepage. Logo has been moved to the`frontend/public` folder.  Anyway, I removed the line in settings that was triggering this error. If you do `git pull` and run the backend server it shouldn't show again.

**Comment by roperi** [comment]
```
2) Accessing Sign Up: For this issue, changing the secret key definition in backend/backend/settings.py worked for me. Specifically, I changed from
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
into
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-default-secret-key')
```

In general, and for security reasons, it's not a good practice to expose your credentials in the settings file. The new line code you wrote is basically doing "in case I don't find the django secret key from the environment variables, default to this secret key".  The reason why it works now for you is because django is not finding the environment variable with the secret key, thus defaulting to the  hardcoded secret key.  Did you follow step one of the Configurations section? It seems you forgot to re-activate the virtual environment before running the backend server again.

**Comment by roperi** [comment]
```
1) Accessing PricingTable: Changing the custom buttons from href to RouterLink in Header.tsx. For example,

            <RouterLink to='/pricing-table' style={{ textDecoration: 'none' }}>
              <Button>Pricing</Button>
            </RouterLink>
```

Well, glad it worked for you!
